apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30007
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
    #status:
    #  loadBalancer:
    #    ingress:
    #    - ip: 172.31.12.165
